
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gehad
 */

public class InstructorCoursesFrame extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    private JsonDatabaseManager dbManager;

    /**
     * Creates new form InstructorCoursesFrame
     */
    public InstructorCoursesFrame() {
        initComponents();
tableModel = (DefaultTableModel) CoursesTable.getModel();

        // Initialize database manager
        dbManager = new JsonDatabaseManager();


        // Optional: set column headers if table has none
        if (tableModel.getColumnCount() == 0) {
            tableModel.setColumnIdentifiers(new String[]{"Course ID", "Title", "Description"});
        }

        // Load all courses
        loadCourses();
    }

    /**
     * Loads all courses from the database into the table
     */
    private void loadCourses() {
        DefaultTableModel model = (DefaultTableModel) CoursesTable.getModel();
        model.setRowCount(0); // Clear existing rows

        for (Course c : dbManager.getCourses()) {
            model.addRow(new Object[]{
                    c.getCourseId(),
                    c.getTitle(),
                    c.getDescription()
            });
        }
        addExtraRows(5);
    }
private void addExtraRows(int extraRows) {
    for (int i = 0; i < extraRows; i++) {
        tableModel.addRow(new Object[]{"", "", ""}); // ID blank for new lessons
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CoursesTable = new javax.swing.JTable();
        CreateButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("==Manage Your Courses==");

        CoursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course ID", "Title", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CoursesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CoursesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CoursesTable);

        CreateButton.setText("Create");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateButton)
                .addGap(30, 30, 30)
                .addComponent(UpdateButton)
                .addGap(29, 29, 29)
                .addComponent(DeleteButton)
                .addGap(30, 30, 30)
                .addComponent(BackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateButton)
                    .addComponent(UpdateButton)
                    .addComponent(DeleteButton)
                    .addComponent(BackButton))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
    int rowCount = tableModel.getRowCount();
    boolean added = false;

    for (int row = 0; row < rowCount; row++) {
        String courseIdCell = (tableModel.getValueAt(row, 0) != null) ? tableModel.getValueAt(row, 0).toString() : "";
        String titleCell = (tableModel.getValueAt(row, 1) != null) ? tableModel.getValueAt(row, 1).toString().trim() : "";

        // Find the first empty row where title is filled but ID is empty
        if (courseIdCell.isEmpty() && !titleCell.isEmpty()) {
            // Generate new courseId
            String courseId = "C" + dbManager.generateCourseId();

            // Get description (can be empty)
            String description = (tableModel.getValueAt(row, 2) != null) ? tableModel.getValueAt(row, 2).toString() : "";

            // Create course object and save to DB
            Course newCourse = new Course(courseId, titleCell, description, "");
            dbManager.addCourse(newCourse);

            // Update table with generated ID
            tableModel.setValueAt(courseId, row, 0);

            added = true;
            break; // only fill one row per click
        }
    }//GEN-LAST:event_CreateButtonActionPerformed
    }
    private void CoursesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoursesTableMouseClicked
       int row = CoursesTable.getSelectedRow();
if (row >= 0) {
    // Get the table model directly from the JTable
    DefaultTableModel model = (DefaultTableModel) CoursesTable.getModel();

    // Retrieve values safely
    String courseId = model.getValueAt(row, 0).toString();
    String title = model.getValueAt(row, 1).toString();
    String desc = model.getValueAt(row, 2).toString();

    // Optionally, show details in text fields if you have them
    // txtCourseId.setText(courseId);
    // txtTitle.setText(title);
    // txtDescription.setText(desc);
}

    }//GEN-LAST:event_CoursesTableMouseClicked

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
int rowCount = tableModel.getRowCount();

    for (int row = 0; row < rowCount; row++) {
        String courseId = tableModel.getValueAt(row, 0).toString();
        String newTitle = tableModel.getValueAt(row, 1).toString();
        String newDescription = tableModel.getValueAt(row, 2).toString();

        // Find course in the database
        Course course = null;
        for (Course c : dbManager.getCourses()) {
            if (c.getCourseId().equals(courseId)) {
                course = c;
                break;
            }
        }
        if (course != null) {
            course.setTitle(newTitle);
            course.setDescription(newDescription);
        }
    }

    // Save all changes to JSON
    dbManager.saveCourses();
    JOptionPane.showMessageDialog(this, "Courses updated successfully!");
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        int selectedRow = CoursesTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a course to delete.");
        return;
    }

    String courseId = tableModel.getValueAt(selectedRow, 0).toString();
    dbManager.getCourses().removeIf(c -> c.getCourseId().equals(courseId));
    dbManager.saveCourses();
    tableModel.removeRow(selectedRow);
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // Close current frame
    this.dispose();

    // Open Instructor Dashboard
    InstructorDashboardFrame dashboard = new InstructorDashboardFrame();
    dashboard.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorCoursesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorCoursesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorCoursesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorCoursesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InstructorCoursesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTable CoursesTable;
    private javax.swing.JButton CreateButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
