
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Abdallah
 */
public class StudentDashboardFrame extends javax.swing.JFrame {
    private Student student;
    private CourseManager courseManager;
    private JsonDatabaseManager db;
   
    /**
     * Creates new form StudentDashboardFrame
     */
   
     public StudentDashboardFrame(User user) {
        initComponents(); // NetBeans GUI builder

        // Check if user is Student
        if (user instanceof Student) {
            this.student = (Student) user;
        } else {
            JOptionPane.showMessageDialog(this, "Error: Logged-in user is not a student!");
            dispose();
            return;
        }

        
        db = new JsonDatabaseManager();

        lblTitle.setText("Welcome, " + student.getUsername());

        // load lists
        refreshLists();
        listEnrolled.addListSelectionListener(e -> {
    if (!e.getValueIsAdjusting()) {
        updateLessonsList();
    }
});

        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
     
     public StudentDashboardFrame() {   // bla
    this(new Student(
            "0",                // fake ID
            "Test Student",     // fake name
            "test@email.com",
            "123",
            new ArrayList<>(),  // empty enrolled courses
            new HashMap<>()     // empty progress
    ));
}
    
    private void refreshLists() {
    List<String> availableNames = new ArrayList<>();
    List<Course> availableCourses = new ArrayList<>();
    List<String> enrolledNames = new ArrayList<>();
    List<Course> enrolledCourses = new ArrayList<>();

    for (Course c : db.getCourses()) {
        int id = Integer.parseInt(c.getCourseId().replaceAll("\\D", ""));
        if (student.getEnrolledCourses().contains(id)) {
            enrolledNames.add(c.getTitle());
            enrolledCourses.add(c);
        } else {
            availableNames.add(c.getTitle());
            availableCourses.add(c);
        }
    }

    listAvailable.putClientProperty("courses", availableCourses);
    listEnrolled.putClientProperty("courses", enrolledCourses);

    listAvailable.setListData(availableNames.toArray(new String[0]));
    listEnrolled.setListData(enrolledNames.toArray(new String[0]));

    // select first enrolled course to auto-update lessons
    if (!enrolledCourses.isEmpty()) {
        listEnrolled.setSelectedIndex(0);
    } else {
        listLessons.setListData(new String[0]);
    }
}
    
    private void updateLessonsList() {
    int index = listEnrolled.getSelectedIndex();
    if (index < 0) {
        listLessons.setListData(new String[0]);
        listLessons.putClientProperty("lessons", null);
        return;
    }

    List<Course> enrolledCourses = (List<Course>) listEnrolled.getClientProperty("courses");
    if (enrolledCourses == null || enrolledCourses.isEmpty()) return;

    Course selectedCourse = enrolledCourses.get(index);

    int courseIdInt = Integer.parseInt(selectedCourse.getCourseId().replaceAll("\\D", ""));
    List<String> completed = student.getProgress().get(courseIdInt);

    List<String> lessonNames = new ArrayList<>();
    for (Lesson l : selectedCourse.getLessons()) {
        String title = (completed != null && completed.contains(l.getLessonId()))
                ? "[✓] " + l.getTitle()
                : l.getTitle();
        lessonNames.add(title);
    }

    listLessons.setListData(lessonNames.toArray(new String[0]));
    listLessons.putClientProperty("lessons", selectedCourse.getLessons());
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblAvailable = new javax.swing.JLabel();
        lblEnrolled = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAvailable = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listEnrolled = new javax.swing.JList<>();
        btnEnroll = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listLessons = new javax.swing.JList<>();
        btnMark = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Welcome ");

        lblAvailable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAvailable.setText("Available Courses");

        lblEnrolled.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEnrolled.setText("Enrolled Courses");

        listAvailable.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listAvailable);

        listEnrolled.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listEnrolled);

        btnEnroll.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnroll.setForeground(new java.awt.Color(255, 0, 0));
        btnEnroll.setText("Enroll");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Lessons");

        listLessons.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listLessons);

        btnMark.setForeground(new java.awt.Color(0, 204, 0));
        btnMark.setText("Mark Complete");
        btnMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblAvailable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEnrolled)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnEnroll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMark)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailable)
                    .addComponent(lblEnrolled))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnroll))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMark)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
       int index = listAvailable.getSelectedIndex();
    if (index < 0) return;

    List<Course> availableCourses = (List<Course>) listAvailable.getClientProperty("courses");
    Course selectedCourse = availableCourses.get(index);//*
     Student realStudent = null;//*
    for (User u : db.getUsers()) {
        if (u instanceof Student s && s.getUserId().equals(student.getUserId())) {
            realStudent = s;
            break;
        }
    }
    if (realStudent == null) {
        JOptionPane.showMessageDialog(this, "Error: Student not found in database!");
        return;
    }
    Course realCourse = null;
    for (Course c : db.getCourses()) {
        if (c.getCourseId().equals(selectedCourse.getCourseId())) {
            realCourse = c;
            break;
        }
    }
    if (realCourse == null) {
        JOptionPane.showMessageDialog(this, "Error: Course not found in database!");
        return;
    }//*
    int courseIdInt = Integer.parseInt(realCourse.getCourseId().replaceAll("\\D", ""));
    if (!realStudent.getEnrolledCourses().contains(courseIdInt)) {
        realStudent.getEnrolledCourses().add(courseIdInt);
        realCourse.getStudents().add(student.getUserId());
        db.saveUsers();
        db.saveCourses();
        this.student = realStudent;
        refreshLists();
         List<Course> enrolledCourses = (List<Course>) listEnrolled.getClientProperty("courses");//*
        for (int i = 0; i < enrolledCourses.size(); i++) {
            if (enrolledCourses.get(i).getCourseId().equals(realCourse.getCourseId())) {
                listEnrolled.setSelectedIndex(i);
                break;
            }
        }
    }
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void btnMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkActionPerformed
       int lessonIndex = listLessons.getSelectedIndex();
    int courseIndex = listEnrolled.getSelectedIndex();
    if (lessonIndex < 0 || courseIndex < 0) return;

    List<Course> enrolledCourses = (List<Course>) listEnrolled.getClientProperty("courses");
    Course selectedCourse = enrolledCourses.get(courseIndex);

    List<Lesson> lessons = (List<Lesson>) listLessons.getClientProperty("lessons");
    Lesson selectedLesson = lessons.get(lessonIndex);

    int courseIdInt = Integer.parseInt(selectedCourse.getCourseId().replaceAll("\\D", ""));
    student.getProgress().putIfAbsent(courseIdInt, new ArrayList<>());
    List<String> completed = student.getProgress().get(courseIdInt);

    if (!completed.contains(selectedLesson.getLessonId())) {
        completed.add(selectedLesson.getLessonId());
        db.saveUsers();
        // refresh lessons list
        listEnrolledValueChanged(null);
    }
    }//GEN-LAST:event_btnMarkActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
       db = new JsonDatabaseManager(); // reload from json
    refreshLists();
    }//GEN-LAST:event_btnRefreshActionPerformed
 
     private void listEnrolledValueChanged(javax.swing.event.ListSelectionEvent evt) {
        int index = listEnrolled.getSelectedIndex();
        if (index < 0) {
            listLessons.setListData(new String[0]);
            return;
        }

        List<Course> enrolledCourses = (List<Course>) listEnrolled.getClientProperty("courses");
        Course selectedCourse = enrolledCourses.get(index);

        int courseIdInt = Integer.parseInt(selectedCourse.getCourseId().replaceAll("\\D", ""));
        List<String> completed = student.getProgress().get(courseIdInt);

        List<String> lessonNames = new ArrayList<>();
        for (Lesson l : selectedCourse.getLessons()) {
            String title = (completed != null && completed.contains(l.getLessonId())) 
                    ? "[✓] " + l.getTitle() 
                    : l.getTitle();
            lessonNames.add(title);
        }
        listLessons.setListData(lessonNames.toArray(new String[0]));
        listLessons.putClientProperty("lessons", selectedCourse.getLessons());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new StudentDashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnMark;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblEnrolled;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> listAvailable;
    private javax.swing.JList<String> listEnrolled;
    private javax.swing.JList<String> listLessons;
    // End of variables declaration//GEN-END:variables
}
